---
- name: Demo Failure Fixed
  hosts: ios
  order: sorted
  gather_facts: false
  tasks:
    - name: Display Configured VLANS
      cisco.ios.ios_command:
        commands:
          - show vlans
      register: vlan_result

    - name: Display VLAN Results
      ansible.builtin.debug:
        var: vlan_result
